import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import Providers from "@/components/providers";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

export const metadata: Metadata = {
	title: "Supabing",
	description: "Generated by Supabing",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontName = DM_Sans({
	weight: ["400", "700"],
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			lang="zh"
			className={cn("antialiased", `${fontName.className}`)}
			suppressHydrationWarning
		>
			<body>
				<div className="texture" />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
