import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import type { Metadata } from "next";
import { Merriweather } from "next/font/google";

export const metadata: Metadata = {
	title: "Supabing",
	description: "Generated by Supabing",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const merriweather = Merriweather({
	weight: ["400", "700"],
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="zh" className={cn("antialiased", `${merriweather.className}`)}>
			<body>{children}</body>
		</html>
	);
}
